/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#12372A',
          dark: '#002116',
          container: '#12372A',
          fixed: '#c3ebd8',
          'fixed-dim': '#a8cfbd',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#7ba190',
        'primary-container': '#12372A',
        'primary-fixed': '#c3ebd8',
        'primary-fixed-dim': '#a8cfbd',
        'on-primary-fixed': '#002116',
        'on-primary-fixed-variant': '#2a4e3f',
        'inverse-primary': '#a8cfbd',

        secondary: {
          DEFAULT: '#C9A24A',
          dark: '#795900',
          container: '#fdd274',
          fixed: '#ffdf9e',
          'fixed-dim': '#ebc165',
        },
        'on-secondary': '#ffffff',
        'secondary-container': '#fdd274',
        'on-secondary-container': '#775800',
        'secondary-fixed': '#ffdf9e',
        'secondary-fixed-dim': '#ebc165',
        'on-secondary-fixed': '#261a00',
        'on-secondary-fixed-variant': '#5b4300',

        tertiary: {
          DEFAULT: '#151e1b',
          container: '#2a332f',
          fixed: '#dbe5df',
          'fixed-dim': '#bfc9c3',
        },
        'on-tertiary': '#ffffff',
        'tertiary-container': '#2a332f',
        'on-tertiary-container': '#919b96',
        'tertiary-fixed': '#dbe5df',
        'tertiary-fixed-dim': '#bfc9c3',
        'on-tertiary-fixed': '#151d1a',
        'on-tertiary-fixed-variant': '#3f4945',

        surface: {
          DEFAULT: '#fcf9f8',
          dim: '#dcd9d9',
          bright: '#fcf9f8',
          container: '#f0eded',
          'container-lowest': '#ffffff',
          'container-low': '#f6f3f2',
          'container-high': '#eae7e7',
          'container-highest': '#e5e2e1',
          variant: '#e5e2e1',
          tint: '#416656',
        },
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container': '#f0eded',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant': '#e5e2e1',
        'surface-tint': '#416656',

        'on-surface': '#1c1b1b',
        'on-surface-variant': '#414844',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#717974',
        'outline-variant': '#c1c8c3',

        brand: {
          green: '#12372A',
          gold: '#C9A24A',
          ivory: '#F7F5EF',
          sage: '#DDE7E1',
          charcoal: '#171717',
        },
      },
      fontFamily: {
        serif: ['"Cormorant Garamond"', '"EB Garamond"', 'Georgia', 'serif'],
        sans: ['Montserrat', 'system-ui', '-apple-system', 'sans-serif'],
        heading: ['"Cormorant Garamond"', '"EB Garamond"', 'Georgia', 'serif'],
        body: ['Montserrat', 'system-ui', '-apple-system', 'sans-serif'],
      },
      spacing: {
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        margin: '4rem',
        'margin-tablet': '2rem',
        'margin-mobile': '1.25rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.75rem',
        'space-xl': '3rem',
      },
    },
  },
  plugins: [],
};
